# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Secondomer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graph = PlotWidget(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(400, 60, 400, 300))
        self.graph.setObjectName("graph")
        self.AddBT = QtWidgets.QPushButton(self.centralwidget)
        self.AddBT.setGeometry(QtCore.QRect(440, 400, 150, 23))
        self.AddBT.setObjectName("AddBT")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 200, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 171, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.Stop_button = QtWidgets.QPushButton(self.widget)
        self.Stop_button.setObjectName("Stop_button")
        self.verticalLayout.addWidget(self.Stop_button)
        self.Start_button = QtWidgets.QPushButton(self.widget)
        self.Start_button.setObjectName("Start_button")
        self.verticalLayout.addWidget(self.Start_button)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddBT.setText(_translate("MainWindow", "Add"))
        self.Stop_button.setText(_translate("MainWindow", "Stop_button"))
        self.Start_button.setText(_translate("MainWindow", "Start_button"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
from pyqtgraph import PlotWidget
